### ISSUE TITLE
Error opening dll

### ISSUE THREAD

**Issue by MrSlinger** [Rhotav/Crypto-Deobfuscator#1]
Hey there. I've got an error when tried opens dll "Object reference not set to an instance of an object"
![image png 7091e5d3452f85c7ec2e30ce3953cd4c](https://user-images.githubusercontent.com/31688188/82739822-b3086000-9d4b-11ea-8592-ffe81dd1345b.png)

**Comment by rhotav** [comment]
Sorry, dll is not supported in this version.
