### ISSUE TITLE
 THE EXECUTABLE IS CLOSED INTEMPESTIVELY

### ISSUE THREAD

**Issue by leodan8744** [Rhotav/Crypto-Deobfuscator#2]
Greetings Rhotav

I have a little problem trying to deobfuscate my executable .exe
I get the following error in the code, please I need your help to deobfuscate

this is the problem that I get 
![ERROR DEOBFUSCATE](https://user-images.githubusercontent.com/66539993/83990327-e54ebb80-a90e-11ea-967b-193e40456ba8.jpg)

the app works fine but it gets stuck there

**Comment by YourBoiBusy** [comment]
same ;(

**Comment by MrJmpl3** [comment]
same

**Comment by nekooee** [comment]
same :(

**Comment by dnvthv** [comment]
Not work for Crypto Obfuscator latest version.

**Comment by ntqueryinformation** [comment]
> Not work for Crypto Obfuscator latest version.

have you got a soulution to the latest crypto version?

**Comment by rhotav** [comment]
I do not intend to work on this obfuscator for a long time. Sorry....
